from fpdf import FPDF
import pandas as pd
import numpy as np
from datetime import datetime


class AuditPDF(FPDF):
    def header(self):
        self.set_fill_color(15, 23, 42)
        self.rect(0, 0, 210, 22, 'F')
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(99, 179, 237)
        self.set_y(6)
        self.cell(0, 10, "DATAAUDIT REPORT", align="C")
        self.set_text_color(255, 255, 255)
        self.ln(18)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by dataaudit  •  Page {self.page_no()}  •  github.com/Usmana74", align="C")

    def section_title(self, title):
        self.set_fill_color(15, 23, 42)
        self.set_text_color(99, 179, 237)
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 8, f"  {title}", ln=True, fill=True)
        self.set_text_color(30, 30, 30)
        self.ln(2)

    def key_value_row(self, label, value, flag_color=None):
        self.set_font("Helvetica", "", 9)
        self.set_fill_color(245, 247, 250)
        self.set_text_color(60, 60, 60)
        self.cell(70, 7, f"  {label}", border=0, fill=True)
        if flag_color:
            self.set_text_color(*flag_color)
        self.cell(0, 7, str(value), border=0, fill=True, ln=True)
        self.set_text_color(60, 60, 60)

    def divider(self):
        self.set_draw_color(220, 220, 220)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)


def generate_pdf(df, filename, output_path):
    pdf = AuditPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Meta info ──────────────────────────────
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"File: {filename}   |   Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}   |   Rows: {df.shape[0]}   |   Columns: {df.shape[1]}", ln=True)
    pdf.ln(4)

    # ── 1. Summary ─────────────────────────────
    pdf.section_title("1. DATASET SUMMARY")
    size_kb = round(df.memory_usage(deep=True).sum() / 1024, 2)
    pdf.key_value_row("Total Rows", df.shape[0])
    pdf.key_value_row("Total Columns", df.shape[1])
    pdf.key_value_row("Memory Usage", f"{size_kb} KB")
    pdf.key_value_row("Numeric Columns", len(df.select_dtypes(include=np.number).columns))
    pdf.key_value_row("Categorical Columns", len(df.select_dtypes(include='object').columns))
    pdf.ln(4)

    # ── 2. Missing Values ──────────────────────
    pdf.section_title("2. MISSING VALUES")
    missing_found = False
    for col in df.columns:
        count = df[col].isnull().sum()
        pct = round((count / len(df)) * 100, 2)
        if count > 0:
            missing_found = True
            if pct >= 50:
                flag = "[XX] Drop recommended"
                color = (220, 50, 50)
            elif pct >= 10:
                flag = "[!!] Impute recommended"
                color = (200, 120, 0)
            else:
                flag = "[OK] Safe to impute"
                color = (30, 150, 80)
            pdf.key_value_row(col, f"{count} missing ({pct}%)  -  {flag}", color)
    if not missing_found:
        pdf.key_value_row("Status", "[OK] No missing values found.", (30, 150, 80))
    pdf.ln(4)

    # ── 3. Duplicates ──────────────────────────
    pdf.section_title("3. DUPLICATE ROWS")
    dup_count = df.duplicated().sum()
    if dup_count == 0:
        pdf.key_value_row("Duplicate Rows", "[OK] None found.", (30, 150, 80))
    else:
        pdf.key_value_row("Duplicate Rows", f"[XX] {dup_count} duplicates detected - run drop_duplicates()", (220, 50, 50))
    pdf.ln(4)

    # ── 4. Outliers ────────────────────────────
    pdf.section_title("4. OUTLIERS (IQR Method)")
    numeric = df.select_dtypes(include=np.number)
    for col in numeric.columns:
        Q1 = numeric[col].quantile(0.25)
        Q3 = numeric[col].quantile(0.75)
        IQR = Q3 - Q1
        count = ((numeric[col] < Q1 - 1.5 * IQR) | (numeric[col] > Q3 + 1.5 * IQR)).sum()
        if count > 0:
            pdf.key_value_row(col, f"[!!] {count} outliers detected", (200, 120, 0))
        else:
            pdf.key_value_row(col, "[OK] Clean", (30, 150, 80))
    pdf.ln(4)

    # ── 5. Skewness ────────────────────────────
    pdf.section_title("5. SKEWNESS")
    for col in numeric.columns:
        skew = round(numeric[col].skew(), 3)
        if abs(skew) < 0.5:
            label = f"{skew}  [OK] Normal"
            color = (30, 150, 80)
        elif abs(skew) < 1:
            label = f"{skew}  [!!] Moderate skew"
            color = (200, 120, 0)
        else:
            label = f"{skew}  [XX] Highly skewed - consider log transform"
            color = (220, 50, 50)
        pdf.key_value_row(col, label, color)
    pdf.ln(4)

    # ── 6. Cardinality ─────────────────────────
    pdf.section_title("6. CARDINALITY (Categorical Columns)")
    cat_cols = df.select_dtypes(include='object').columns
    if len(cat_cols) == 0:
        pdf.key_value_row("Status", "No categorical columns found.")
    for col in cat_cols:
        unique = df[col].nunique()
        pct = round((unique / len(df)) * 100, 1)
        if pct > 80:
            flag = f"{unique} unique ({pct}%)  [XX] Likely ID column"
            color = (220, 50, 50)
        elif unique > 20:
            flag = f"{unique} unique ({pct}%)  [!!] High cardinality"
            color = (200, 120, 0)
        else:
            flag = f"{unique} unique ({pct}%)  [OK] Good for encoding"
            color = (30, 150, 80)
        pdf.key_value_row(col, flag, color)
    pdf.ln(4)

    # ── 7. Data Types ──────────────────────────
    pdf.section_title("7. DATA TYPES")
    for col, dtype in df.dtypes.items():
        pdf.key_value_row(col, str(dtype))
    pdf.ln(4)

    # ── 8. Correlation ─────────────────────────
    pdf.section_title("8. HIGH CORRELATION (≥ 0.8)")
    corr = numeric.corr().abs()
    upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))
    found = False
    for col in upper.columns:
        for idx in upper.index:
            val = upper.loc[idx, col]
            if pd.notna(val) and val >= 0.8:
                found = True
                pdf.key_value_row(f"{idx} ↔ {col}", f"{round(val, 3)}  [!!] Consider dropping one", (200, 120, 0))
    if not found:
        pdf.key_value_row("Status", "[OK] No high correlations found.", (30, 150, 80))
    pdf.ln(4)

    # ── 9. Memory Usage ────────────────────────
    pdf.section_title("9. MEMORY USAGE PER COLUMN")
    mem = df.memory_usage(deep=True)
    for col, usage in mem.items():
        pdf.key_value_row(str(col), f"{round(usage / 1024, 3)} KB")
    pdf.ln(4)

    pdf.output(output_path)